services:
  oryn-app:
    container_name: oryn-app
    depends_on:
      - oryn-db
      - oryn-lgtm
    build:
      dockerfile: Dockerfile
      context: .
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8889/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - oryn-sandbox
    ports:
      - "8888:8888"
      - "8889:8889"
    expose:
      - "8888"
      - "8889"
    volumes:
      - .:/app
    env_file:
      - .env


  oryn-db:
    container_name: oryn-db
    image: mysql:8
    restart: always
    networks:
      - oryn-sandbox
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - oryn-db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: oryn
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  oryn-lgtm:
    container_name: oryn-lgtm
    image: grafana/otel-lgtm:latest
    networks:
      - oryn-sandbox
    ports:
      - "3000:3000"
      - "4317:4317"
      - "9090:9090"
    environment:
      - GF_LOG_LEVEL=info
    volumes:
      - oryn-lgtm-data:/var/lib/grafana

volumes:
  oryn-db-data:
    driver: local
  oryn-lgtm-data:
    driver: local

networks:
  oryn-sandbox:
    driver: bridge