metric:
  interval: 3s
  exporters:
    stdout:
      enabled: true
      options:
        pretty_print: false
    otlp_grpc:
      enabled: true
      options:
        endpoint: ${OTLP_GRPC_ENDPOINT}
        insecure: true