log:
  level: debug
  source: true
  exporters:
    stdout:
      enabled: true
      options:
        pretty_print: false
    otlp_grpc:
      enabled: true
      options:
        endpoint: ${OTLP_GRPC_ENDPOINT}
        insecure: true
metric:
  interval: 3s
  exporters:
    stdout:
      enabled: false
      options:
        pretty_print: false
    otlp_grpc:
      enabled: true
      options:
        endpoint: ${OTLP_GRPC_ENDPOINT}
        insecure: true
trace:
  exporters:
    stdout:
      enabled: false
      options:
        pretty_print: true
    otlp_grpc:
      enabled: true
      options:
        endpoint: ${OTLP_GRPC_ENDPOINT}
        insecure: true