trace:
  exporters:
    stdout:
      enabled: false
      options:
        pretty_print: true
    otlp_grpc:
      enabled: true
      options:
        endpoint: ${OTLP_GRPC_ENDPOINT}
        insecure: true